In [1]:
import numpy as np

In [2]:
np.zeros(21)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
 0., 0., 0., 0.])

In [3]:
u = np.arange(1,89,3)
u

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [4]:
z = np.array([5,3,6,3,7,3,7,3])
z

array([5, 3, 6, 3, 7, 3, 7, 3])

In [5]:
t = np.linspace(0,10,num=5)
t

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [8]:
mc_x = np.array([[2,5],[6,8]])
mc_y = np.array([[11,46],[102,32]])
mc_x

array([[2, 5],
 [6, 8]])

In [9]:
mc_y

array([[ 11, 46],
 [102, 32]])

In [11]:
mc_z = mc_x*mc_y
mc_z

array([[ 22, 230],
 [612, 256]])

In [12]:
mc_z[mc_z<235]

array([ 22, 230])